name: Nala
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Execute code
      run: node nala.js
      env:
        SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
        EMAIL_TO: ${{secrets.EMAIL_TO}}
        EMAIL_FROM: ${{secrets.EMAIL_FROM}}
        EMAIL_TEMPLATE_ID: ${{secrets.EMAIL_TEMPLATE_ID}}
        ENV: ${{secrets.ENV}}